# Generated by Django 3.2.7 on 2023-10-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20231005_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='cost_currency',
        ),
        migrations.AlterField(
            model_name='job',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
