# Generated by Django 3.2.7 on 2023-10-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20231005_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='balance_currency',
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
